apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: python-basic-169957645
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: python-basic-169957645
    app.kubernetes.io/part-of: test-app-169957645
  name: python-basic-169957645
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: python-basic-169957645
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: python-basic-169957645
    spec:
      containers:
      - image: quay.io/hacdev/gjwgsvxd-tenant/test-app-169957645/python-basic-169957645@sha256:74489e224f62a4a8646415e951b4a27d623439917ff8f35660404973c727cc64
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
